/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-04 · Crear cuenta y obtener token */
        post: operations["AuthController_signup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-04 · Iniciar sesión */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-22 · Listar perfiles de paciente de la cuenta */
        get: operations["MembershipController_myPatients_v1"];
        put?: never;
        /**
         * UC-01 · Registrar paciente
         * @description Crea el perfil del paciente y vincula al creador como consent-holder. Idempotente por operationId (NFR-34).
         */
        post: operations["MembershipController_registerPatient_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * UC-22 · Ver la ficha del paciente
         * @description Ficha completa. Requiere vínculo con el paciente (cualquier rol); linkRole indica el rol de quien consulta.
         */
        get: operations["MembershipController_patientRecord_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * UC-22 · Editar la ficha del paciente
         * @description Set parcial de la ficha (naturalmente idempotente, sin operationId). Solo vínculos consent-holder o manager; queda auditado (quién, cuándo, qué campos).
         */
        patch: operations["MembershipController_updatePatient_v1"];
        trace?: never;
    };
    "/api/v1/patients/{id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * UC-22 · Círculo del paciente
         * @description Cuentas vinculadas al paciente (displayName/email) con el rol de su vínculo. Visible para cualquier vinculado; una cuenta sin vínculo recibe 403.
         */
        get: operations["MembershipController_patientCircle_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * UC-02 · Registrar cuidador
         * @description Crea el perfil profesional en estado pending. No visible en el marketplace hasta UC-19.
         */
        post: operations["CaregiverController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregivers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-02 · Ver mi perfil y estado de aprobación */
        get: operations["CaregiverController_myProfile_v1"];
        /**
         * UC-02 A2 · Re-enviar postulación tras rechazo
         * @description Corrige los datos y re-envía. Solo desde estado rejected: el perfil vuelve a pending, se limpia el motivo de rechazo y las certificaciones vuelven a "no verificada". Naturalmente idempotente.
         */
        put: operations["CaregiverController_resubmit_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * UC-02 A3 · Editar el perfil aprobado
         * @description Set parcial de foto, disponibilidad, tarifas, zona y modalidades sin re-aprobación (el perfil sigue aprobado y visible). La tarifa es efectivo-fechada (NFR-03/23): cada cambio agrega una versión al historial y las solicitudes existentes conservan su tarifa pinneada. Credenciales (nombre/especialidades/certificaciones) no se editan por esta vía.
         */
        patch: operations["CaregiverController_updateApproved_v1"];
        trace?: never;
    };
    "/api/v1/admin/caregivers/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-19 · Cola de cuidadores pendientes de aprobación */
        get: operations["AdminCaregiverController_pending_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cuidadores con filtro por estado (paginado) */
        get: operations["AdminCaregiverController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-19 · Detalle del cuidador (con documentación para verificar) */
        get: operations["AdminCaregiverController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-19 · Aprobar cuenta (la publica en el marketplace) */
        post: operations["AdminCaregiverController_approve_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-19 · Rechazar cuenta (con motivo) */
        post: operations["AdminCaregiverController_reject_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers/{id}/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** UC-19 · Actualizar insignias de verificación (niveles independientes) */
        put: operations["AdminCaregiverController_badges_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OQ-8/NFR-31 · Desactivar (ocultar) cuidador; dispara el ripple encolado a Hiring */
        post: operations["AdminCaregiverController_deactivate_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/caregivers/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OQ-8 · Reactivar cuidador desactivado (vuelve a visible) */
        post: operations["AdminCaregiverController_reactivate_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-03 · Listar invitaciones emitidas (estado y vencimiento) */
        get: operations["InvitationController_list_v1"];
        put?: never;
        /** UC-03 · Emitir invitación (30 min, un solo uso) */
        post: operations["InvitationController_issue_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-03 · Revocar invitación (la deja inutilizable) */
        post: operations["InvitationController_revoke_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-03 · Previsualizar invitación */
        get: operations["InvitationController_preview_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-03 · Confirmar invitación y crear el vínculo */
        post: operations["InvitationController_confirm_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir imagen de perfil (jpeg/png/webp, máx 5MB) → URL pública */
        post: operations["FilesController_upload_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/caregivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-06 · Buscar cuidadores (solo aprobados, filtros combinables) */
        get: operations["MarketplaceController_search_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/caregivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-07 · Ver perfil de cuidador */
        get: operations["MarketplaceController_profile_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-08 · Listar favoritos */
        get: operations["MarketplaceController_favorites_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{caregiverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-08 · Marcar favorito (idempotente) */
        post: operations["MarketplaceController_addFavorite_v1"];
        /** UC-08 · Quitar favorito */
        delete: operations["MarketplaceController_removeFavorite_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hiring-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-09 · Mis solicitudes */
        get: operations["MarketplaceController_myRequests_v1"];
        put?: never;
        /** UC-09 · Crear solicitud de contratación (una por paciente) */
        post: operations["MarketplaceController_createRequest_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hiring-requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * UC-09 A2 · Cancelar solicitud pendiente (solo el solicitante)
         * @description Cancela una solicitud mientras está pendiente; queda en estado terminal `cancelled` y el cuidador deja de verla como pendiente.
         */
        post: operations["MarketplaceController_cancel_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hiring-requests/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-09 · Finalizar / marcar como pagada (cierra el servicio) */
        post: operations["MarketplaceController_complete_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/caregivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-16 · Cuidadores del paciente (vigentes e históricos) */
        get: operations["MarketplaceController_history_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregiver/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-10 · Solicitudes recibidas */
        get: operations["CaregiverRequestsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregiver/requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-10 · Aceptar solicitud (crea la asignación, UC-05) */
        post: operations["CaregiverRequestsController_accept_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregiver/requests/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-10 · Rechazar solicitud */
        post: operations["CaregiverRequestsController_decline_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hiring-requests/{requestId}/review-caregiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-17 · Calificar al cuidador (servicio finalizado) */
        post: operations["ReviewController_reviewCaregiver_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hiring-requests/{requestId}/review-patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-21 · Calificar al paciente (servicio finalizado) */
        post: operations["ReviewController_reviewPatient_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregivers/{id}/reputation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-07 · Reputación del cuidador (reseñas visibles + promedio) */
        get: operations["ReviewController_caregiverReputation_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{id}/reputation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-10/21 · Reputación del paciente (visible para el cuidador) */
        get: operations["ReviewController_patientReputation_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-12 · Registrar signos vitales (alerta si fuera de rango) */
        post: operations["CareRecordController_vitals_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-13 · Registrar medicación administrada */
        post: operations["CareRecordController_medication_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-20 · Registrar novedad / comentario */
        post: operations["CareRecordController_note_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-18 · Mis notificaciones */
        get: operations["NotificationController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-18 · Contador de no leídas (badge de la campana) */
        get: operations["NotificationController_unread_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * UC-18 · Marcar todas las notificaciones como leídas
         * @description Marca todas las no leídas del destinatario. Idempotente: repetir devuelve updated=0.
         */
        post: operations["NotificationController_readAll_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * UC-18 · Config del canal push
         * @description Clave pública VAPID para suscribirse. enabled=false: el cliente no ofrece push, la campana sigue sola.
         */
        get: operations["NotificationController_pushConfig_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-18 · Mis suscripciones push (por cuenta, revocables) */
        get: operations["NotificationController_listPushSubscriptions_v1"];
        put?: never;
        /**
         * UC-18 flujo 1 · Suscribir este navegador al push
         * @description Idempotente por endpoint único: re-suscribir renueva claves/dueño, nunca duplica.
         */
        post: operations["NotificationController_subscribePush_v1"];
        /**
         * UC-18 · Revocar la suscripción push de un endpoint
         * @description A1: el usuario apaga el push; las alertas siguen en la campana. Idempotente: repetir devuelve removed=0.
         */
        delete: operations["NotificationController_unsubscribePush_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-18 · Marcar notificación como leída */
        post: operations["NotificationController_markRead_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-12 A3 · Items en cuarentena del paciente (NFR-30, visibles al círculo) */
        get: operations["QuarantineController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/quarantine/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-12 A3 · Aprobar: entra al historial con su measuredAt original (NFR-36) */
        post: operations["QuarantineController_approve_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/quarantine/{id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** UC-12 A3 · Descartar: queda marcado con traza, nunca se borra */
        post: operations["QuarantineController_discard_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-14 · Estado actual (último valor por métrica, con as-of) */
        get: operations["CareConsultController_state_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-14 · Historial cronológico (vitales, medicación, novedades) */
        get: operations["CareConsultController_history_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/metrics/{metricKey}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** UC-15 · Serie temporal de una métrica (para graficar) */
        get: operations["CareConsultController_series_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogos de la plataforma
         * @description Enumeraciones y catálogo de métricas (con unidad y rangos por defecto) para dropdowns y validación del cliente.
         */
        get: operations["ReferenceController_getCatalogs_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ops/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** NFR-14 · Ejecutar el barrido de vencidos ahora (asignaciones, solicitudes, reseñas) */
        post: operations["OpsController_sweep_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NFR-33 · Listar el audit log (paginado, filtros por actor/acción) */
        get: operations["AuditController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas operativas (cuidadores por estado, contrataciones, asignaciones activas) */
        get: operations["DashboardController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupDto: {
            /** @example familiar@test.com */
            email: string;
            /** @example S3gura!123 */
            password: string;
            /**
             * @example family
             * @enum {string}
             */
            role: "patient" | "family" | "caregiver";
            /** @example Juan Díaz */
            displayName: string;
        };
        AuthResponseDto: {
            accessToken: string;
            /** Format: uuid */
            accountId: string;
            email: string;
            /** @enum {string} */
            role: "patient" | "family" | "caregiver" | "admin";
            displayName: string;
        };
        LoginDto: {
            /** @example familiar@test.com */
            email: string;
            /** @example S3gura!123 */
            password: string;
        };
        EmergencyContactDto: {
            /** @example María Díaz */
            name: string;
            /** @example +54 11 5555-5555 */
            phone: string;
            /** @example hija */
            relationship?: string;
        };
        RegisterPatientDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /** @example Rosa Díaz */
            fullName: string;
            /**
             * @description Fecha de nacimiento ISO (YYYY-MM-DD). La edad se deriva de acá.
             * @example 1948-03-10
             */
            birthDate: string;
            /** @example https://cdn.keru.app/p/rosa.jpg */
            photoUrl?: string;
            /** @example Hipertensión */
            mainCondition: string;
            /** @example 0+ */
            bloodGroup?: string;
            /**
             * @example [
             *       "Penicilina"
             *     ]
             */
            allergies: string[];
            emergencyContact: components["schemas"]["EmergencyContactDto"];
        };
        PatientResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example Rosa Díaz */
            fullName: string;
            /**
             * @description Edad derivada de la fecha de nacimiento.
             * @example 78
             */
            age: number;
            /**
             * Format: uuid
             * @description Si se detectó un posible duplicado del mismo humano (residuo #21), su id; el cliente puede ofrecer vincular/mergear.
             */
            duplicateCandidateId?: string;
        };
        PatientRecordDto: {
            /** Format: uuid */
            id: string;
            /** @example Rosa Díaz */
            fullName: string;
            /**
             * @description Fecha de nacimiento ISO (YYYY-MM-DD).
             * @example 1948-03-10
             */
            birthDate: string;
            /**
             * @description Edad derivada de la fecha de nacimiento.
             * @example 78
             */
            age: number;
            /** @example https://cdn.keru.app/p/rosa.jpg */
            photoUrl?: string;
            /** @example Hipertensión */
            mainCondition: string;
            /** @example 0+ */
            bloodGroup?: string;
            /**
             * @example [
             *       "Penicilina"
             *     ]
             */
            allergies: string[];
            /**
             * @example {
             *       "name": "María Díaz",
             *       "phone": "+54 11 5555-5555",
             *       "relationship": "hija"
             *     }
             */
            emergencyContact: Record<string, never>;
            /**
             * @description Rol del vínculo de la cuenta que consulta.
             * @enum {string}
             */
            linkRole: "consent-holder" | "manager" | "viewer";
        };
        PatientLinkDto: {
            /** Format: uuid */
            accountId: string;
            /** @example María Díaz */
            displayName: string;
            /** @example maria@example.com */
            email: string;
            /**
             * @description Rol del vínculo con el paciente.
             * @enum {string}
             */
            role: "consent-holder" | "manager" | "viewer";
            /**
             * Format: date-time
             * @description Cuándo se creó el vínculo.
             */
            since: string;
        };
        UpdatePatientDto: {
            /** @example Rosa Díaz */
            fullName?: string;
            /**
             * @description Fecha de nacimiento ISO (YYYY-MM-DD). No puede ser futura.
             * @example 1948-03-10
             */
            birthDate?: string;
            /** @example https://cdn.keru.app/p/rosa.jpg */
            photoUrl?: string;
            /** @example Hipertensión */
            mainCondition?: string;
            /** @example 0+ */
            bloodGroup?: string;
            /**
             * @example [
             *       "Penicilina"
             *     ]
             */
            allergies?: string[];
            emergencyContact?: components["schemas"]["EmergencyContactDto"];
        };
        CertificationDto: {
            /** @example Enfermería */
            type: string;
            /** @example Universidad de Buenos Aires */
            institution: string;
            /** @example 2015 */
            year: number;
        };
        AvailabilityDto: {
            /**
             * @description 0=domingo .. 6=sábado
             * @example 1
             */
            dayOfWeek: number;
            /** @example 08:00 */
            from: string;
            /** @example 16:00 */
            to: string;
        };
        RatesDto: {
            /** @example 3500 */
            ratePerHour: number;
            /**
             * @default ARS
             * @example ARS
             */
            currency: string;
            /** @example Incluye acompañamiento nocturno */
            description?: string;
        };
        RegisterCaregiverDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /** @example Laura Gómez */
            displayName: string;
            /** @example http://localhost:4566/keru-media/images/abc.jpg */
            photoUrl?: string;
            /**
             * @example [
             *       "elder-care",
             *       "palliative"
             *     ]
             */
            specialties: ("elder-care" | "post-surgical" | "chronic-illness" | "disability" | "palliative" | "pediatric" | "rehabilitation" | "companionship")[];
            certifications: components["schemas"]["CertificationDto"][];
            availability: components["schemas"]["AvailabilityDto"][];
            rates: components["schemas"]["RatesDto"];
            /** @example Palermo, CABA */
            zone: string;
            /**
             * @example [
             *       "home",
             *       "hospital"
             *     ]
             */
            modalities: ("home" | "hospital")[];
        };
        CaregiverResponseDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            photoUrl?: string | null;
            certifications: Record<string, never>[];
            availability: Record<string, never>[];
            rates: Record<string, never>;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "deactivated";
            specialties: string[];
            zone: string;
            modalities: string[];
            /**
             * @example {
             *       "certifications": true,
             *       "identity": false,
             *       "background": false
             *     }
             */
            badges: Record<string, never>;
            rejectionReason?: Record<string, never>;
        };
        UpdateCaregiverProfileDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /** @example http://localhost:4566/keru-media/images/abc.jpg */
            photoUrl?: string;
            availability?: components["schemas"]["AvailabilityDto"][];
            rates?: components["schemas"]["RatesDto"];
            /** @example Palermo, CABA */
            zone?: string;
            /**
             * @example [
             *       "home",
             *       "hospital"
             *     ]
             */
            modalities?: ("home" | "hospital")[];
        };
        CaregiverDetailDto: {
            /** Format: uuid */
            id: string;
            accountId: string;
            displayName: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "deactivated";
            specialties: string[];
            certifications: Record<string, never>[];
            availability: Record<string, never>[];
            rates: Record<string, never>;
            zone: string;
            modalities: string[];
            badges: Record<string, never>;
            rejectionReason?: Record<string, never>;
            reviewedBy?: Record<string, never>;
            reviewedAt?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
        };
        RejectCaregiverDto: {
            /** @example Certificación de RCP ilegible */
            reason: string;
        };
        SetBadgesDto: {
            /** @example true */
            certifications?: boolean;
            /** @example true */
            identity?: boolean;
            /** @example false */
            background?: boolean;
        };
        DeactivateCaregiverDto: {
            /** @example Denuncia de un familiar */
            reason?: string;
        };
        CreateInvitationDto: {
            /**
             * @description Invitado nombrado (se desafía su identidad al confirmar).
             * @example hermana@test.com
             */
            invitedEmail: string;
            /**
             * @default viewer
             * @enum {string}
             */
            role: "manager" | "viewer";
        };
        InvitationResponseDto: {
            token: string;
            /** Format: uuid */
            patientId: string;
            invitedEmail: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "revoked";
            /**
             * Format: date-time
             * @description Vence a los 30 minutos de emitida (OQ-2).
             */
            expiresAt: string;
            /** @description Deep link para compartir (abre app o web). */
            link: string;
        };
        EmittedInvitationDto: {
            token: string;
            /** Format: uuid */
            patientId: string;
            invitedEmail: string;
            /** @enum {string} */
            roleToGrant: "consent-holder" | "manager" | "viewer";
            /** @enum {string} */
            status: "pending" | "accepted" | "revoked";
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Cuenta que emitió la invitación (habilitada a revocarla). */
            invitedByAccountId: string;
        };
        InvitationConfirmedDto: {
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            role: "consent-holder" | "manager" | "viewer";
        };
        UploadedImageDto: {
            /** @description URL pública de la imagen subida (usar como photoUrl) */
            url: string;
        };
        CaregiverCardDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @description Foto de perfil (UC-06) */
            photoUrl?: string;
            specialties: string[];
            zone: string;
            modalities: string[];
            ratePerHour: number;
            currency: string;
            badges: Record<string, never>;
            /** @description true si está en los favoritos de la cuenta */
            isFavorite?: boolean;
            /** @description Promedio de reseñas reveladas, 0 si no tiene (UC-06 criterio 3) */
            ratingAverage?: number;
            /** @description Cantidad de reseñas reveladas */
            ratingCount?: number;
        };
        CaregiverProfileDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @description Foto de perfil (UC-06) */
            photoUrl?: string;
            specialties: string[];
            zone: string;
            modalities: string[];
            ratePerHour: number;
            currency: string;
            badges: Record<string, never>;
            /** @description true si está en los favoritos de la cuenta */
            isFavorite?: boolean;
            /** @description Promedio de reseñas reveladas, 0 si no tiene (UC-06 criterio 3) */
            ratingAverage?: number;
            /** @description Cantidad de reseñas reveladas */
            ratingCount?: number;
            certifications: Record<string, never>[];
            availability: Record<string, never>[];
        };
        CreateRequestDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /** Format: uuid */
            patientId: string;
            /** Format: uuid */
            caregiverId: string;
            /** @enum {string} */
            modality: "home" | "hospital";
            /** @example 2026-08-01T08:00:00Z */
            startDate: string;
            /** @example 2026-08-15T18:00:00Z */
            endDate: string;
            /** @example Requiere movilidad reducida */
            specialRequirements?: string;
            /**
             * @example {
             *       "phone": "+54 11 5555-5555"
             *     }
             */
            contactData: Record<string, never>;
        };
        RequestResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patientId: string;
            /** Format: uuid */
            caregiverId: string;
            /** @description Nombre del paciente (visible para el cuidador, UC-10) */
            patientName?: string;
            /** @description Nombre del cuidador (visible para el solicitante) */
            caregiverName?: string;
            modality: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            specialRequirements?: string;
            /** @description Datos de contacto del solicitante. Para el cuidador solo con solicitud aceptada/en curso (UC-10). */
            contactData?: Record<string, never>;
            /** @enum {string} */
            status: "pending" | "accepted" | "declined" | "cancelled" | "in-progress" | "finished" | "expired";
            /** @description Tarifa pinneada al solicitar (NFR-03/23) */
            ratePerHourSnapshot: string;
        };
        CaregiverHistoryItemDto: {
            /** Format: uuid */
            assignmentId: string;
            /** Format: uuid */
            caregiverId: string;
            caregiverName?: string;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            /** @enum {string} */
            status: "active" | "historical";
        };
        SubmitReviewDto: {
            /** @example 5 */
            rating: number;
            /** @example Muy atenta y puntual */
            comment?: string;
        };
        ReviewDto: {
            /** Format: uuid */
            id: string;
            rating: number;
            comment?: Record<string, never>;
            /** @enum {string} */
            subjectType: "caregiver" | "patient";
            revealed: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ReputationDto: {
            /**
             * @example {
             *       "average": 4.5,
             *       "count": 2
             *     }
             */
            aggregate: Record<string, never>;
            reviews: components["schemas"]["ReviewDto"][];
        };
        MetricValueDto: {
            /**
             * @example blood-pressure-systolic
             * @enum {string}
             */
            metricKey: "blood-pressure-systolic" | "blood-pressure-diastolic" | "heart-rate" | "temperature" | "oxygen-saturation" | "glucose";
            /** @example 120 */
            value: number;
        };
        RecordVitalsDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /**
             * @description Tiempo de medición ISO. Default: ahora.
             * @example 2026-07-21T10:00:00Z
             */
            measuredAt?: string;
            values: components["schemas"]["MetricValueDto"][];
        };
        RecordResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "vitals" | "medication" | "note";
            /** Format: uuid */
            patientId: string;
            /** Format: date-time */
            measuredAt: string;
            authorRole: string;
            /**
             * @description recorded: entró al historial. quarantined: llegada tardía no autorizada en cuarentena (NFR-30), pendiente de resolución del círculo — nunca se descarta en silencio.
             * @enum {string}
             */
            status: "recorded" | "quarantined";
        };
        RecordMedicationDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /** @example 2026-07-21T10:00:00Z */
            measuredAt?: string;
            /** @example Enalapril */
            medication: string;
            /** @example 10 mg */
            dose: string;
            /** @example 08:00 */
            schedule?: string;
            /** @example Tomada con el desayuno */
            observations?: string;
        };
        RecordNoteDto: {
            /**
             * @description Identidad de operación provista por el cliente (NFR-34). Un reintento con el mismo valor no duplica el efecto.
             * @example op-8f3a2c1e
             */
            operationId: string;
            /** @example 2026-07-21T10:00:00Z */
            measuredAt?: string;
            /** @example Durmió bien, comió poco en el almuerzo */
            text: string;
        };
        NotificationDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "alert" | "note";
            /** Format: uuid */
            patientId: string;
            title: string;
            body: string;
            read: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        MarkAllReadResponseDto: {
            /** @example true */
            ok: boolean;
            /**
             * @description Cantidad de notificaciones que pasaron de no leída a leída (0 si se repite: idempotente).
             * @example 3
             */
            updated: number;
        };
        PushConfigDto: {
            /** @description false si el servidor no tiene claves VAPID: solo campana. */
            enabled: boolean;
            /** @description Clave pública VAPID (applicationServerKey). */
            publicKey: string | null;
        };
        PushSubscriptionDto: {
            /** Format: uuid */
            id: string;
            endpoint: string;
            /** Format: date-time */
            createdAt: string;
        };
        PushKeysDto: {
            /** @description Clave pública ECDH del navegador. */
            p256dh: string;
            /** @description Secreto de autenticación del navegador. */
            auth: string;
        };
        SubscribePushDto: {
            /** @description URL del push service del navegador. */
            endpoint: string;
            keys: components["schemas"]["PushKeysDto"];
        };
        UnsubscribePushResponseDto: {
            /** @example true */
            ok: boolean;
            /**
             * @description 0 si el endpoint ya no estaba suscripto.
             * @example 1
             */
            removed: number;
        };
        QuarantinedRecordDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            type: "vitals" | "medication" | "note";
            /**
             * Format: date-time
             * @description Tiempo de medición original (NFR-36).
             */
            measuredAt: string;
            /**
             * Format: date-time
             * @description Tiempo de llegada.
             */
            receivedAt: string;
            authorAccountId: string;
            authorRole: string;
            /** @example no-authority-at-measurement */
            reason: string;
            /** @enum {string} */
            status: "pending" | "approved" | "discarded";
            /** @description Contenido del registro según type. */
            data: Record<string, never>;
            resolvedByAccountId?: Record<string, never> | null;
            resolvedAt?: Record<string, never> | null;
            /**
             * Format: uuid
             * @description Si se aprobó: registro promovido al historial.
             */
            approvedRecordId?: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    MembershipController_myPatients_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"][];
                };
            };
        };
    };
    MembershipController_registerPatient_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPatientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
        };
    };
    MembershipController_patientRecord_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRecordDto"];
                };
            };
        };
    };
    MembershipController_updatePatient_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRecordDto"];
                };
            };
        };
    };
    MembershipController_patientCircle_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientLinkDto"][];
                };
            };
        };
    };
    CaregiverController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCaregiverDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    CaregiverController_myProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    CaregiverController_resubmit_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCaregiverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    CaregiverController_updateApproved_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaregiverProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    AdminCaregiverController_pending_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"][];
                };
            };
        };
    };
    AdminCaregiverController_list_v1: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected" | "deactivated";
                /** @description Busca por nombre o zona */
                q?: string;
                pageSize?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminCaregiverController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverDetailDto"];
                };
            };
        };
    };
    AdminCaregiverController_approve_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    AdminCaregiverController_reject_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectCaregiverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    AdminCaregiverController_badges_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBadgesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    AdminCaregiverController_deactivate_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeactivateCaregiverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    AdminCaregiverController_reactivate_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverResponseDto"];
                };
            };
        };
    };
    InvitationController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmittedInvitationDto"][];
                };
            };
        };
    };
    InvitationController_issue_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponseDto"];
                };
            };
        };
    };
    InvitationController_revoke_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmittedInvitationDto"];
                };
            };
        };
    };
    InvitationController_preview_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Datos de la invitación para la pantalla de confirmación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationController_confirm_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationConfirmedDto"];
                };
            };
        };
    };
    FilesController_upload_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedImageDto"];
                };
            };
        };
    };
    MarketplaceController_search_v1: {
        parameters: {
            query?: {
                careType?: "elder-care" | "post-surgical" | "chronic-illness" | "disability" | "palliative" | "pediatric" | "rehabilitation" | "companionship";
                modality?: "home" | "hospital";
                zone?: string;
                minRatePerHour?: number;
                maxRatePerHour?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverCardDto"][];
                };
            };
        };
    };
    MarketplaceController_profile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverProfileDto"];
                };
            };
        };
    };
    MarketplaceController_favorites_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverCardDto"][];
                };
            };
        };
    };
    MarketplaceController_addFavorite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caregiverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarketplaceController_removeFavorite_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caregiverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarketplaceController_myRequests_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"][];
                };
            };
        };
    };
    MarketplaceController_createRequest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"];
                };
            };
        };
    };
    MarketplaceController_cancel_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"];
                };
            };
        };
    };
    MarketplaceController_complete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"];
                };
            };
        };
    };
    MarketplaceController_history_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverHistoryItemDto"][];
                };
            };
        };
    };
    CaregiverRequestsController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"][];
                };
            };
        };
    };
    CaregiverRequestsController_accept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"];
                };
            };
        };
    };
    CaregiverRequestsController_decline_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponseDto"];
                };
            };
        };
    };
    ReviewController_reviewCaregiver_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
        };
    };
    ReviewController_reviewPatient_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
        };
    };
    ReviewController_caregiverReputation_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationDto"];
                };
            };
        };
    };
    ReviewController_patientReputation_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationDto"];
                };
            };
        };
    };
    CareRecordController_vitals_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordVitalsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    CareRecordController_medication_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMedicationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    CareRecordController_note_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordNoteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    NotificationController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDto"][];
                };
            };
        };
    };
    NotificationController_unread_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationController_readAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkAllReadResponseDto"];
                };
            };
        };
    };
    NotificationController_pushConfig_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushConfigDto"];
                };
            };
        };
    };
    NotificationController_listPushSubscriptions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionDto"][];
                };
            };
        };
    };
    NotificationController_subscribePush_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribePushDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionDto"];
                };
            };
        };
    };
    NotificationController_unsubscribePush_v1: {
        parameters: {
            query: {
                /** @description Endpoint (URL) de la suscripción a revocar. */
                endpoint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsubscribePushResponseDto"];
                };
            };
        };
    };
    NotificationController_markRead_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuarantineController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinedRecordDto"][];
                };
            };
        };
    };
    QuarantineController_approve_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinedRecordDto"];
                };
            };
        };
    };
    QuarantineController_discard_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantinedRecordDto"];
                };
            };
        };
    };
    CareConsultController_state_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado actual del paciente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CareConsultController_history_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial por tiempo de medición */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CareConsultController_series_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                metricKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Puntos {measuredAt, value} ordenados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferenceController_getCatalogs_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    OpsController_sweep_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cantidades transicionadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditController_list_v1: {
        parameters: {
            query?: {
                actor?: string;
                action?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de entradas de auditoría */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas del back-office */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
